
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const POST_LOAD = 'POST_LOAD'
export const POST_VOTE = 'POST_VOTE'
export const POST_EDIT = 'POST_EDIT'
export const POST_UPDATE = 'POST_UPDATE'
export const POST_DELETE = 'POST_DELETE'
export const POST_PUBLIC = 'public'
export const POST_HIDDEN = 'hidden'
export const POST_PRIVATE_LOAD = 'POST_PRIVATE_LOAD'
export const POST_PRIVATE_GET = 'POST_PRIVATE_GET'
export const POST_LOAD_MORE = 'POST_LOAD_MORE'
export const POST_APPEND = 'POST_APPEND'
export const POST_CREATE = 'POST_CREATE'